### ISSUE TITLE
Typo in script in sample sheet breaks merge

### ISSUE THREAD

**Issue by benkloester** [knmnyn/GMail-Mail-Merge#11]
The sample Gmail Mail Merge++ spreadsheet linked to from readme.md contains a version of this script with a typo that causes merge to fail with the error `ReferenceError: msgOptionHash is not defined at Code:242:11 at Array.forEach (<anonymous>) at sendEmails_ (Code:222:9) at Code:162:27 at Array.forEach (<anonymous>) at sendEma…`.

The typo is on line 238: `msgOptionHash['cc'] = cachedCC;` note the missing s - it should be `msgOptionsHash`

**Comment by knmnyn** [comment]
Hi @benkloester , thanks for the bug report.  I appreciate the request to fix.  

Closes #11.
