### ISSUE TITLE
General workflow clarification, small redundancies.

### ISSUE THREAD

**Issue by achray** [knmnyn/GMail-Mail-Merge#7]
Hello Dr Min,

I've been going through Code.gs to better understand how to enhance the mail merge for our purposes. I am, however, a little unclear with what our desired workflow will be.

My understanding of the mail merge's use is to allow us to send student-specific emails that fall under a set number of templates. For this purpose, I would think that we need to build the following:
1. A way to port students' "progress" into Google Sheets. By "progress" I mean whatever metric required to assign each student to a relevant email template for the current week/period.
2. A mail merge script that, given these groups, sends per-student customized emails to them at the right time (cron) that, perhaps, bcc'es their tutors if required.

Is my understanding of the workflow correct? If so, I intend to streamline the code to better serve this purpose. Generally, there are some small redundancies in the code and between the sheets (e.g. duplicate cc columns) that I am also working to remove.

**Comment by achray** [comment]
Recently saw your post on slack, we'll discuss these kinds of matters further then!

**Comment by knmnyn** [comment]
@achray  That's partially correct.  We want to build the target Mail Merge to generically support more richer functionality mail merge with Gmail and then utilise it for doing the weekly nudge, and other forms of email communication to students; i.e., mailing exam results, project consultation, etc.

**Comment by knmnyn** [comment]
The multiple cc columns are to support generic (overall) cc:s and per-recipient (individual) cc:s.  E.g., I might want to cc: a coordinator on all emails (overall) but then cc: the particular tutor for a particular student (individual).

So the two are not redundant but need to be merged.  The documentation needs to reflect that.  My bad on that!

**Comment by knmnyn** [comment]
For your 1st item, you are right.  There needs to be some way of porting the student progress into a GSheet from Coursemology.  That is a separate item that does concern your student XP position but not this particular repo.

**Comment by knmnyn** [comment]
Discussion moved to Slack.
